name: Trigger resume updated

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger submodule update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: hungthai1401/hungthai1401.github.io
          event-type: resume_updated